spring:
  profiles:
    active:
      - common
      - db
      - sso
server:
  port: 8081
logging:
  level:
    org.springframework.security: debug
syhthems:
  security:
    sso-server: https://sso.syhthems.sunriseydy.top/sso
  cors:
    allowed-origins: '*' # 设置允许的源
    allowed-methods: GET, PUT, POST, DELETE # 设置允许的请求方法
    allowed-headers: '*' # 设置允许的头