package top.sunriseydy.syhthems.db.mapper;

import top.sunriseydy.syhthems.db.base.CustomBaseMapper;
import top.sunriseydy.syhthems.db.model.RoleMenu;

/**
 * @author dengmin
 * Generated by MBG
 */
public interface RoleMenuMapper extends CustomBaseMapper<RoleMenu> {
}