package top.sunriseydy.syhthems.db.mapper;

import top.sunriseydy.syhthems.db.base.CustomBaseMapper;
import top.sunriseydy.syhthems.db.model.User;

/**
 * @author dengmin
 * Generated by MBG
 */
public interface UserMapper extends CustomBaseMapper<User> {
}